### ISSUE TITLE
UX defects: 越用越深色

### ISSUE THREAD

**Issue by pantinker** [hkbus/mobile-bus-app#8]
粒子風暴：按制越用越深色

![IMG_20231205_190224_008.jpg](https://github.com/hkbus/mobile-bus-app/assets/152949070/ad0e86d0-8f70-4640-aa1f-71b7b373c5c2)

![IMG_20231205_190224_276.jpg](https://github.com/hkbus/mobile-bus-app/assets/152949070/b044614f-582d-4054-b718-dc1c8a0123e7)

![IMG_20231205_190224_458.jpg](https://github.com/hkbus/mobile-bus-app/assets/152949070/a74801a6-757e-4084-afca-42b3e0400ec8)

![IMG_20231205_190224_236.jpg](https://github.com/hkbus/mobile-bus-app/assets/152949070/c4906efc-304e-438a-8030-a883fcd98509)

**Comment by chunlaw** [comment]
Fixed
